In [1]:
import pandas as pd

In [3]:
companies_info = pd.read_csv("simfin_data/us-companies.csv", sep=";")

In [5]:
companies_info.iloc[6052]["Business Summary"]

"Based in Ann Arbor, Michigan, Zomedica is a veterinary health company creating products for dogs and cats by focusing on the unmet needs of clinical veterinarians. Zomedica\\'s product portfolio will include innovative diagnostics and medical devices that emphasize patient health and practice health. It is Zomedica\\'s mission to provide veterinarians the opportunity to increase productivity and grow revenue while better serving the animals in their care."

In [11]:
# Installation: pip install simfin
# import simfin package
import simfin as sf

# Set your API-key for downloading data.
sf.set_api_key('ea74c1b5-ad8f-4c16-b7a4-b4ce1f7747a9')

# Set the local directory where data-files are stored.
# The directory will be created if it does not already exist.
sf.set_data_dir('~/simfin_data/')

# Download the data from the SimFin server and load into a Pandas DataFrame.
mapping_df = sf.load_industries()

Dataset "industries" on disk (0 days old).
- Loading from disk ... Done!

/Users/paul/github/NeuroFinance/env_agent_analytics/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

In [13]:
mapping_df

                              Industry           Sector
IndustryId
100001             Industrial Products      Industrials
100002               Business Services      Industrials
100003      Engineering & Construction      Industrials
100004                Waste Management      Industrials
100005         Industrial Distribution      Industrials
...                                ...              ...
110004                 Metals & Mining  Basic Materials
110005              Building Materials  Basic Materials
110006                            Coal  Basic Materials
110007                           Steel  Basic Materials
111001            Diversified Holdings            Other

[74 rows x 2 columns]

In [12]:
import pandas as pd

# Assuming 'data_df' is your main dataset with an 'IndustryId' column
# and 'mapping_df' is your lookup table with IndustryId as the index or a column.

# If IndustryId is the index in mapping_df:
merged = pd.merge(companies_info, mapping_df, left_on='IndustryId', right_index=True, how='left')

# If IndustryId is a column in mapping_df:
# merged = pd.merge(data_df, mapping_df, left_on='IndustryId', right_on='IndustryId', how='left')

# Now check for rows where mapping details (e.g., 'Industry') are missing:
missing = merged[merged['Industry'].isna()]

if missing.empty:
    print("Every IndustryId in your dataset has a corresponding mapping!")
else:
    print("Missing mapping for the following IndustryIds:")
    print(missing['IndustryId'].unique())

Missing mapping for the following IndustryIds:
[nan]

In [14]:
missing

,Ticker,SimFinId,Company Name,IndustryId,ISIN,End of financial year (month),Number Employees,Business Summary,Market,CIK,Main Currency,Industry,Sector
0,NaN,17162642,NaN,NaN,NaN,NaN,NaN,NaN,us,1913577.0,USD,NaN,NaN
1,NaN,17429327,NaN,NaN,NaN,NaN,NaN,NaN,us,1894951.0,USD,NaN,NaN
2,NaN,17590527,NaN,NaN,NaN,NaN,NaN,NaN,us,1847355.0,USD,NaN,NaN
3,NaN,17590533,NaN,NaN,NaN,NaN,NaN,NaN,us,1856161.0,USD,NaN,NaN
4,NaN,17596599,NaN,NaN,NaN,NaN,NaN,NaN,us,1862463.0,USD,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5933,WTMK,90931,WHITEMARK HOMES INC,NaN,NaN,12.0,NaN,NaN,us,42284.0,USD,NaN,NaN
5968,XHUA,662912,XINHUA CHINA LTD,NaN,NaN,6.0,NaN,NaN,us,1104904.0,USD,NaN,NaN
5969,XING,663216,China Xingbang Industry Group Inc.,NaN,NaN,12.0,NaN,NaN,us,1521222.0,USD,NaN,NaN
5972,XLGROUP,903527,XL GROUP LTD,NaN,NaN,12.0,NaN,NaN,us,875159.0,USD,NaN,NaN
6039,ZINCQ,287827,Horsehead Holding Corp,NaN,NaN,12.0,NaN,NaN,us,1385544.0,USD,NaN,NaN

In [22]:
financial_df = pd.read_csv("/Users/paul/github/NeuroFinance/app/backend/data/balance_data_2020_2023.csv",index_col="Unnamed: 0")

In [23]:
merged_data = pd.merge(financial_df, merged, on='Ticker', how='left')

# Check for any financial records that didn't match a company entry:
missing = merged_data[merged_data['Industry'].isna()]
if not missing.empty:
    print("Missing industry mapping for the following tickers:")
    print(missing['Ticker'].unique())
else:
    print("All financial records have an associated industry mapping!")

Missing industry mapping for the following tickers:
['DHRM' 'ISSM' 'ONCYF' 'QVC' 'SFY' 'VRML']

In [24]:
merged_data

,Ticker,Fiscal Year,Report Date,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,...,IndustryId,ISIN,End of financial year (month),Number Employees,Business Summary,Market,CIK,Main Currency,Industry,Sector
0,AA,2019,2019-12-31,8.790000e+08,659010141.0,1.644000e+09,3.530000e+09,7.916000e+09,1.113000e+09,2.072000e+09,...,110004.0,US0138721065,12.0,12900.0,Alcoa Corp is an integrated aluminum company. ...,us,1675149.0,USD,Metals & Mining,Basic Materials
1,AA,2020,2020-12-31,1.607000e+09,556977743.0,1.398000e+09,4.520000e+09,7.190000e+09,1.051000e+09,2.099000e+09,...,110004.0,US0138721065,12.0,12900.0,Alcoa Corp is an integrated aluminum company. ...,us,1675149.0,USD,Metals & Mining,Basic Materials
2,AA,2021,2021-12-31,1.814000e+09,881913876.0,1.956000e+09,5.026000e+09,6.623000e+09,1.199000e+09,2.177000e+09,...,110004.0,US0138721065,12.0,12900.0,Alcoa Corp is an integrated aluminum company. ...,us,1675149.0,USD,Metals & Mining,Basic Materials
3,AA,2022,2022-12-31,1.363000e+09,909421884.0,2.427000e+09,5.250000e+09,6.493000e+09,1.122000e+09,1.891000e+09,...,110004.0,US0138721065,12.0,12900.0,Alcoa Corp is an integrated aluminum company. ...,us,1675149.0,USD,Metals & Mining,Basic Materials
4,AA,2023,2023-12-31,9.440000e+08,809198655.0,2.158000e+09,4.405000e+09,6.785000e+09,9.790000e+08,1.986000e+09,...,110004.0,US0138721065,12.0,12900.0,Alcoa Corp is an integrated aluminum company. ...,us,1675149.0,USD,Metals & Mining,Basic Materials
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9793,ZYXI,2019,2019-12-31,1.404000e+07,5833000.0,2.378000e+06,2.256600e+07,4.683818e+06,2.664663e+09,4.853000e+06,...,106004.0,US98986M1036,12.0,768.0,"Zynex, Inc. engages in the design, manufacture...",us,846475.0,USD,Medical Devices,Healthcare
9794,ZYXI,2020,2020-12-31,3.917300e+07,13837000.0,8.635000e+06,6.302300e+07,7.937073e+06,2.664663e+09,7.227000e+06,...,106004.0,US98986M1036,12.0,768.0,"Zynex, Inc. engages in the design, manufacture...",us,846475.0,USD,Medical Devices,Healthcare
9795,ZYXI,2021,2021-12-31,4.261200e+07,28632000.0,1.075600e+07,8.268900e+07,1.853476e+07,2.664663e+09,4.839900e+07,...,106004.0,US98986M1036,12.0,768.0,"Zynex, Inc. engages in the design, manufacture...",us,846475.0,USD,Medical Devices,Healthcare
9796,ZYXI,2022,2022-12-31,2.014400e+07,35063000.0,1.348400e+07,6.955900e+07,1.500549e+07,2.664663e+09,4.473200e+07,...,106004.0,US98986M1036,12.0,768.0,"Zynex, Inc. engages in the design, manufacture...",us,846475.0,USD,Medical Devices,Healthcare
9797,ZYXI,2023,2023-12-31,4.457900e+07,26838000.0,1.310600e+07,8.785500e+07,1.562371e+07,2.664663e+09,4.593500e+07,...,106004.0,US98986M1036,12.0,768.0,"Zynex, Inc. engages in the design, manufacture...",us,846475.0,USD,Medical Devices,Healthcare